[workspace]
members = [
  "crates/app_api",
  "crates/app",
  "crates/core",
  "crates/db",
  "crates/ingest",
  "crates/http_api",
  "apps/cli",
  "apps/desktop/src-tauri",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
